---
- name: Configure EC2 instance
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Run GitLab Runner in a Docker container
      community.docker.docker_container:
        name: gitlab-runner
        image: gitlab/gitlab-runner:latest
        state: started
        restart_policy: always
        volumes:
          - /srv/gitlab-runner/config:/etc/gitlab-runner
          - /var/run/docker.sock:/var/run/docker.sock

    - name: Register GitLab Runner
      command: >
        docker exec -i gitlab-runner gitlab-runner register
        --non-interactive
        --url "{{ gitlab_url }}"
        --registration-token "{{ gitlab_token }}"
        --tag-list "{{ gitlab_tags }}"
        --executor "docker"
        --docker-image "docker:latest"
        --docker-privileged
      register: register_output
      ignore_errors: true

    - name: Display registration output
      debug:
        var: register_output.stdout_lines